import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.thirteen}>
            <h1>Hunting Coder</h1>
          </div>
        </div>
        <div className={styles.imgWrapper}>
          <Image src={'/homeimg.jpg'} className={styles.myImg} alt='home image' width={237} height={158} />
        </div>
        <div className={styles.description}>
          <p>A blog for Hunting coders by a hunting coder</p>
          <div>Created by Hunting coder</div>
        </div>
        <h1 className={styles.blogHead}>
          Latest Blog
        </h1>
        <div className={styles.grid}>
          <div className={styles.card}>
            <div className="blogitems">
              <h2 className={inter.className}>
                How to learn JavaScript in 2023?
              </h2>
              <p className={inter.className}>
                JavaScript is the languague use to desing logic on the web.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
